# Generated by Django 4.0.3 on 2022-03-15 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('newsid', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=40)),
                ('subtitle', models.CharField(max_length=80)),
                ('article', models.TextField()),
                ('date', models.DateField()),
                ('topics', models.CharField(max_length=80)),
            ],
        ),
    ]
