# Generated by Django 4.0.3 on 2022-03-15 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_remove_news_newsid_news_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('subtitle', models.CharField(max_length=80)),
                ('text', models.TextField()),
                ('date', models.DateField()),
                ('topics', models.CharField(max_length=80)),
            ],
        ),
        migrations.DeleteModel(
            name='news',
        ),
    ]
